#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
PYTHON_BIN="$PROJECT_DIR/.venv/bin/python"
PROFILE="${1:-}"
INTERVAL_SEC="2"

case "$PROFILE" in
  lotte_chemical_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_LOTTE_CHEMICAL_MIDDAY_ENABLED=true
    CONFIRM="011170_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  lx_semicon_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_LX_SEMICON_MORNING_ENABLED=true
    CONFIRM="108320_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  lotte_chemical_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_LOTTE_CHEMICAL_MORNING_ENABLED=true
    CONFIRM="011170_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  lotte_chemical_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_LOTTE_CHEMICAL_AFTERNOON_ENABLED=true
    CONFIRM="011170_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_heavy_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_HEAVY_MIDDAY_ENABLED=true
    CONFIRM="010140_MIDDAY_TWO_LEG_LIVE"
    ;;
  samsung_heavy_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_HEAVY_AFTERNOON_ENABLED=true
    CONFIRM="010140_AFTERNOON_TWO_LEG_LIVE"
    ;;
  sk_eternix_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_ETERNIX_MIDDAY_ENABLED=true
    CONFIRM="475150_MIDDAY_TWO_LEG_LIVE"
    ;;
  mirae_asset_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_MIRAE_ASSET_MORNING_ENABLED=true
    CONFIRM="006800_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  hanwha_ocean_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_HANWHA_OCEAN_LATE_MORNING_ENABLED=true
    CONFIRM="042660_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kepco_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KEPCO_AFTERNOON_ENABLED=true
    CONFIRM="015760_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sk_eternix_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_ETERNIX_MORNING_ENABLED=true
    CONFIRM="475150_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  mirae_asset_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_MIRAE_ASSET_MIDDAY_ENABLED=true
    CONFIRM="006800_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sk_eternix_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_ETERNIX_AFTERNOON_ENABLED=true
    CONFIRM="475150_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_heavy_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_HEAVY_MORNING_ENABLED=true
    CONFIRM="010140_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_ea_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_EA_MORNING_ENABLED=true
    CONFIRM="028050_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_ea_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_EA_LATE_MORNING_ENABLED=true
    CONFIRM="028050_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_ea_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_EA_AFTERNOON_ENABLED=true
    CONFIRM="028050_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kepco_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KEPCO_LATE_MORNING_ENABLED=true
    CONFIRM="015760_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kepco_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KEPCO_MIDDAY_ENABLED=true
    CONFIRM="015760_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sk_eternix_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SK_ETERNIX_LATE_MORNING_ENABLED=true
    CONFIRM="475150_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  mirae_asset_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_MIRAE_ASSET_LATE_MORNING_ENABLED=true
    CONFIRM="006800_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  kepco_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_KEPCO_MORNING_ENABLED=true
    CONFIRM="015760_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sd_biosensor_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SD_BIOSENSOR_MORNING_ENABLED=true
    CONFIRM="137310_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sd_biosensor_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SD_BIOSENSOR_LATE_MORNING_ENABLED=true
    CONFIRM="137310_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sd_biosensor_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SD_BIOSENSOR_MIDDAY_ENABLED=true
    CONFIRM="137310_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_ea_midday)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_EA_MIDDAY_ENABLED=true
    CONFIRM="028050_MIDDAY_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  fan_ocean_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_FAN_OCEAN_MORNING_ENABLED=true
    CONFIRM="028670_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  fan_ocean_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_FAN_OCEAN_LATE_MORNING_ENABLED=true
    CONFIRM="028670_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  samsung_heavy_late_morning)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SAMSUNG_HEAVY_LATE_MORNING_ENABLED=true
    CONFIRM="010140_LATE_MORNING_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  fan_ocean_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_FAN_OCEAN_AFTERNOON_ENABLED=true
    CONFIRM="028670_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  sd_biosensor_afternoon)
    export KORSTOCKSCAN_LOW_PRICE_TWO_LEG_SD_BIOSENSOR_AFTERNOON_ENABLED=true
    CONFIRM="137310_AFTERNOON_TWO_LEG_LIVE"
    INTERVAL_SEC="6"
    ;;
  *)
    echo "unsupported low-price two-leg profile: $PROFILE" >&2
    exit 2
    ;;
esac

exec env PYTHONPATH="$PROJECT_DIR" "$PYTHON_BIN" -m \
  src.trading.low_price_two_leg.service \
  --profile "$PROFILE" \
  --live \
  --confirm "$CONFIRM" \
  --interval-sec "$INTERVAL_SEC"
