#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="${KORSTOCKSCAN_PROJECT_DIR:-/home/ubuntu/KORStockScan}"
SCRIPT_DIR="$PROJECT_DIR/deploy"
source "$SCRIPT_DIR/runtime_release_set_lock.sh"

TARGET_DIR="/etc/systemd/system"
TIMERS=(
  korstockscan-low-price-two-leg-lotte-chemical-midday-preflight.timer
  korstockscan-low-price-two-leg-lotte-chemical-midday.timer
  korstockscan-low-price-two-leg-lx-semicon-morning-preflight.timer
  korstockscan-low-price-two-leg-lx-semicon-morning.timer
  korstockscan-low-price-two-leg-lotte-chemical-morning-preflight.timer
  korstockscan-low-price-two-leg-lotte-chemical-morning.timer
  korstockscan-low-price-two-leg-lotte-chemical-afternoon-preflight.timer
  korstockscan-low-price-two-leg-lotte-chemical-afternoon.timer
  korstockscan-low-price-two-leg-tym-late-morning-preflight.timer
  korstockscan-low-price-two-leg-tym-late-morning.timer
  korstockscan-low-price-two-leg-samsung-heavy-midday-preflight.timer
  korstockscan-low-price-two-leg-samsung-heavy-midday.timer
  korstockscan-low-price-two-leg-samsung-heavy-afternoon-preflight.timer
  korstockscan-low-price-two-leg-samsung-heavy-afternoon.timer
  korstockscan-low-price-two-leg-daewoo-ec-midday-preflight.timer
  korstockscan-low-price-two-leg-daewoo-ec-midday.timer
  korstockscan-low-price-two-leg-daewoo-ec-afternoon-preflight.timer
  korstockscan-low-price-two-leg-daewoo-ec-afternoon.timer
  korstockscan-low-price-two-leg-sk-eternix-midday-preflight.timer
  korstockscan-low-price-two-leg-sk-eternix-midday.timer
  korstockscan-low-price-two-leg-mirae-asset-morning-preflight.timer
  korstockscan-low-price-two-leg-mirae-asset-morning.timer
  korstockscan-low-price-two-leg-jeju-semiconductor-morning-preflight.timer
  korstockscan-low-price-two-leg-jeju-semiconductor-morning.timer
  korstockscan-low-price-two-leg-hanwha-ocean-late-morning-preflight.timer
  korstockscan-low-price-two-leg-hanwha-ocean-late-morning.timer
  korstockscan-low-price-two-leg-kakao-morning-preflight.timer
  korstockscan-low-price-two-leg-kakao-morning.timer
  korstockscan-low-price-two-leg-kepco-afternoon-preflight.timer
  korstockscan-low-price-two-leg-kepco-afternoon.timer
  korstockscan-low-price-two-leg-kakao-late-morning-preflight.timer
  korstockscan-low-price-two-leg-kakao-late-morning.timer
  korstockscan-low-price-two-leg-sk-eternix-morning-preflight.timer
  korstockscan-low-price-two-leg-sk-eternix-morning.timer
  korstockscan-low-price-two-leg-mirae-asset-midday-preflight.timer
  korstockscan-low-price-two-leg-mirae-asset-midday.timer
  korstockscan-low-price-two-leg-sk-eternix-afternoon-preflight.timer
  korstockscan-low-price-two-leg-sk-eternix-afternoon.timer
  korstockscan-low-price-two-leg-samsung-heavy-morning-preflight.timer
  korstockscan-low-price-two-leg-samsung-heavy-morning.timer
  korstockscan-low-price-two-leg-kakao-midday-preflight.timer
  korstockscan-low-price-two-leg-kakao-midday.timer
  korstockscan-low-price-two-leg-sk-telecom-afternoon-preflight.timer
  korstockscan-low-price-two-leg-sk-telecom-afternoon.timer
  korstockscan-low-price-two-leg-samsung-ea-morning-preflight.timer
  korstockscan-low-price-two-leg-samsung-ea-morning.timer
  korstockscan-low-price-two-leg-samsung-ea-late-morning-preflight.timer
  korstockscan-low-price-two-leg-samsung-ea-late-morning.timer
  korstockscan-low-price-two-leg-samsung-ea-afternoon-preflight.timer
  korstockscan-low-price-two-leg-samsung-ea-afternoon.timer
  korstockscan-low-price-two-leg-sk-telecom-late-morning-preflight.timer
  korstockscan-low-price-two-leg-sk-telecom-late-morning.timer
  korstockscan-low-price-two-leg-sk-telecom-morning-preflight.timer
  korstockscan-low-price-two-leg-sk-telecom-morning.timer
  korstockscan-low-price-two-leg-hanse-morning-preflight.timer
  korstockscan-low-price-two-leg-hanse-morning.timer
  korstockscan-low-price-two-leg-hanse-afternoon-preflight.timer
  korstockscan-low-price-two-leg-hanse-afternoon.timer
  korstockscan-low-price-two-leg-cj-cgv-midday-preflight.timer
  korstockscan-low-price-two-leg-cj-cgv-midday.timer
  korstockscan-low-price-two-leg-cj-cgv-afternoon-preflight.timer
  korstockscan-low-price-two-leg-cj-cgv-afternoon.timer
  korstockscan-low-price-two-leg-tym-midday-preflight.timer
  korstockscan-low-price-two-leg-tym-midday.timer
  korstockscan-low-price-two-leg-tym-afternoon-preflight.timer
  korstockscan-low-price-two-leg-tym-afternoon.timer
  korstockscan-low-price-two-leg-cj-cgv-late-morning-preflight.timer
  korstockscan-low-price-two-leg-cj-cgv-late-morning.timer
  korstockscan-low-price-two-leg-kepco-late-morning-preflight.timer
  korstockscan-low-price-two-leg-kepco-late-morning.timer
  korstockscan-low-price-two-leg-kepco-midday-preflight.timer
  korstockscan-low-price-two-leg-kepco-midday.timer
  korstockscan-low-price-two-leg-hanse-late-morning-preflight.timer
  korstockscan-low-price-two-leg-hanse-late-morning.timer
  korstockscan-low-price-two-leg-hanse-midday-preflight.timer
  korstockscan-low-price-two-leg-hanse-midday.timer
  korstockscan-low-price-two-leg-nhn-afternoon-preflight.timer
  korstockscan-low-price-two-leg-nhn-afternoon.timer
  korstockscan-low-price-two-leg-youngone-morning-preflight.timer
  korstockscan-low-price-two-leg-youngone-morning.timer
  korstockscan-low-price-two-leg-youngone-afternoon-preflight.timer
  korstockscan-low-price-two-leg-youngone-afternoon.timer
  korstockscan-low-price-two-leg-sk-eternix-late-morning-preflight.timer
  korstockscan-low-price-two-leg-sk-eternix-late-morning.timer
  korstockscan-low-price-two-leg-mirae-asset-late-morning-preflight.timer
  korstockscan-low-price-two-leg-mirae-asset-late-morning.timer
  korstockscan-low-price-two-leg-kepco-morning-preflight.timer
  korstockscan-low-price-two-leg-kepco-morning.timer
  korstockscan-low-price-two-leg-nhn-morning-preflight.timer
  korstockscan-low-price-two-leg-nhn-morning.timer
  korstockscan-low-price-two-leg-nhn-late-morning-preflight.timer
  korstockscan-low-price-two-leg-nhn-late-morning.timer
  korstockscan-low-price-two-leg-sd-biosensor-morning-preflight.timer
  korstockscan-low-price-two-leg-sd-biosensor-morning.timer
  korstockscan-low-price-two-leg-sd-biosensor-late-morning-preflight.timer
  korstockscan-low-price-two-leg-sd-biosensor-late-morning.timer
  korstockscan-low-price-two-leg-sd-biosensor-midday-preflight.timer
  korstockscan-low-price-two-leg-sd-biosensor-midday.timer
  korstockscan-low-price-two-leg-samsung-ea-midday-preflight.timer
  korstockscan-low-price-two-leg-samsung-ea-midday.timer
  korstockscan-low-price-two-leg-fan-ocean-morning-preflight.timer
  korstockscan-low-price-two-leg-fan-ocean-morning.timer
  korstockscan-low-price-two-leg-fan-ocean-late-morning-preflight.timer
  korstockscan-low-price-two-leg-fan-ocean-late-morning.timer
  korstockscan-low-price-two-leg-samsung-heavy-late-morning-preflight.timer
  korstockscan-low-price-two-leg-samsung-heavy-late-morning.timer
  korstockscan-low-price-two-leg-cj-cgv-morning-preflight.timer
  korstockscan-low-price-two-leg-cj-cgv-morning.timer
  korstockscan-low-price-two-leg-fan-ocean-afternoon-preflight.timer
  korstockscan-low-price-two-leg-fan-ocean-afternoon.timer
  korstockscan-low-price-two-leg-youngone-midday-preflight.timer
  korstockscan-low-price-two-leg-youngone-midday.timer
  korstockscan-low-price-two-leg-sk-telecom-midday-preflight.timer
  korstockscan-low-price-two-leg-sk-telecom-midday.timer
  korstockscan-low-price-two-leg-nhn-midday-preflight.timer
  korstockscan-low-price-two-leg-nhn-midday.timer
  korstockscan-low-price-two-leg-tym-morning-preflight.timer
  korstockscan-low-price-two-leg-tym-morning.timer
  korstockscan-low-price-two-leg-sd-biosensor-afternoon-preflight.timer
  korstockscan-low-price-two-leg-sd-biosensor-afternoon.timer
)
SERVICES=(
  korstockscan-low-price-two-leg@lotte_chemical_midday.service
  korstockscan-low-price-two-leg-preflight@lotte_chemical_midday.service
  korstockscan-low-price-two-leg@lx_semicon_morning.service
  korstockscan-low-price-two-leg-preflight@lx_semicon_morning.service
  korstockscan-low-price-two-leg@lotte_chemical_morning.service
  korstockscan-low-price-two-leg-preflight@lotte_chemical_morning.service
  korstockscan-low-price-two-leg@lotte_chemical_afternoon.service
  korstockscan-low-price-two-leg-preflight@lotte_chemical_afternoon.service
  korstockscan-low-price-two-leg@samsung_heavy_midday.service
  korstockscan-low-price-two-leg@samsung_heavy_afternoon.service
  korstockscan-low-price-two-leg@daewoo_ec_midday.service
  korstockscan-low-price-two-leg@daewoo_ec_afternoon.service
  korstockscan-low-price-two-leg@sk_eternix_midday.service
  korstockscan-low-price-two-leg-preflight@samsung_heavy_midday.service
  korstockscan-low-price-two-leg-preflight@samsung_heavy_afternoon.service
  korstockscan-low-price-two-leg-preflight@daewoo_ec_midday.service
  korstockscan-low-price-two-leg-preflight@daewoo_ec_afternoon.service
  korstockscan-low-price-two-leg-preflight@sk_eternix_midday.service
  korstockscan-low-price-two-leg@mirae_asset_morning.service
  korstockscan-low-price-two-leg@hanwha_ocean_late_morning.service
  korstockscan-low-price-two-leg-preflight@mirae_asset_morning.service
  korstockscan-low-price-two-leg-preflight@hanwha_ocean_late_morning.service
  korstockscan-low-price-two-leg@kepco_afternoon.service
  korstockscan-low-price-two-leg@sk_eternix_morning.service
  korstockscan-low-price-two-leg@mirae_asset_midday.service
  korstockscan-low-price-two-leg@sk_eternix_afternoon.service
  korstockscan-low-price-two-leg-preflight@kepco_afternoon.service
  korstockscan-low-price-two-leg-preflight@sk_eternix_morning.service
  korstockscan-low-price-two-leg-preflight@mirae_asset_midday.service
  korstockscan-low-price-two-leg-preflight@sk_eternix_afternoon.service
  korstockscan-low-price-two-leg@samsung_heavy_morning.service
  korstockscan-low-price-two-leg@samsung_ea_morning.service
  korstockscan-low-price-two-leg@samsung_ea_late_morning.service
  korstockscan-low-price-two-leg@samsung_ea_afternoon.service
  korstockscan-low-price-two-leg-preflight@samsung_heavy_morning.service
  korstockscan-low-price-two-leg-preflight@samsung_ea_morning.service
  korstockscan-low-price-two-leg-preflight@samsung_ea_late_morning.service
  korstockscan-low-price-two-leg-preflight@samsung_ea_afternoon.service
  korstockscan-low-price-two-leg@kepco_late_morning.service
  korstockscan-low-price-two-leg-preflight@kepco_late_morning.service
  korstockscan-low-price-two-leg@kepco_midday.service
  korstockscan-low-price-two-leg-preflight@kepco_midday.service
  korstockscan-low-price-two-leg@sk_eternix_late_morning.service
  korstockscan-low-price-two-leg-preflight@sk_eternix_late_morning.service
  korstockscan-low-price-two-leg@mirae_asset_late_morning.service
  korstockscan-low-price-two-leg-preflight@mirae_asset_late_morning.service
  korstockscan-low-price-two-leg@kepco_morning.service
  korstockscan-low-price-two-leg-preflight@kepco_morning.service
  korstockscan-low-price-two-leg@sd_biosensor_morning.service
  korstockscan-low-price-two-leg-preflight@sd_biosensor_morning.service
  korstockscan-low-price-two-leg@sd_biosensor_late_morning.service
  korstockscan-low-price-two-leg-preflight@sd_biosensor_late_morning.service
  korstockscan-low-price-two-leg@sd_biosensor_midday.service
  korstockscan-low-price-two-leg-preflight@sd_biosensor_midday.service
  korstockscan-low-price-two-leg@samsung_ea_midday.service
  korstockscan-low-price-two-leg-preflight@samsung_ea_midday.service
  korstockscan-low-price-two-leg@fan_ocean_morning.service
  korstockscan-low-price-two-leg-preflight@fan_ocean_morning.service
  korstockscan-low-price-two-leg@fan_ocean_late_morning.service
  korstockscan-low-price-two-leg-preflight@fan_ocean_late_morning.service
  korstockscan-low-price-two-leg@samsung_heavy_late_morning.service
  korstockscan-low-price-two-leg-preflight@samsung_heavy_late_morning.service
  korstockscan-low-price-two-leg@fan_ocean_afternoon.service
  korstockscan-low-price-two-leg-preflight@fan_ocean_afternoon.service
  korstockscan-low-price-two-leg@sd_biosensor_afternoon.service
  korstockscan-low-price-two-leg-preflight@sd_biosensor_afternoon.service
)
FILES=(
  korstockscan-low-price-two-leg@.service
  korstockscan-low-price-two-leg-preflight@.service
  "${TIMERS[@]}"
)

if [[ "${EUID}" -ne 0 ]]; then
  echo "run as root: sudo $0"
  exit 2
fi

runtime_release_set_lock_acquire "$PROJECT_DIR"

/bin/systemctl disable --now "${TIMERS[@]}" 2>/dev/null || true
/bin/systemctl stop "${SERVICES[@]}" 2>/dev/null || true
for unit in "${FILES[@]}"; do
  /bin/rm -f "$TARGET_DIR/$unit"
done
/bin/systemctl daemon-reload

echo "removed only lower-price two-leg units; state, authority, and held-position records were preserved"
